#!/usr/bin/env bash
# Honeypot comparison experiment - per-node bootstrap.
#
# Run the SAME file on EVERY node. Everything that determines a node's
# behaviour lives in this script, so identical file == identical measurement
# conditions.
#
#   sudo NODE_ID=host-a ADMIN_CIDR=203.0.113.7/32 ./bootstrap.sh
#
# Target platform: Debian 13 (systemd, nftables, ssh.socket).
set -euo pipefail

NODE_ID="${NODE_ID:?set NODE_ID, a short stable name for this host, e.g. host-a}"
ADMIN_CIDR="${ADMIN_CIDR:?set ADMIN_CIDR, e.g. 203.0.113.7/32 - your management IP}"
MGMT_PORT="${MGMT_PORT:-62222}"
MOVE_SSH="${MOVE_SSH:-yes}"
PREFIX="${PREFIX:-/opt/honeypot}"
DATA="${DATA:-/var/lib/honeypot}"
SRC="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# --- Port contract (MUST be identical on every node) -----------------------
# Emulated by OpenCanary -> accepted, full interaction is logged.
HP_TCP="21 22 23 80 1433 3306 3389 5900 6379 8080 9418"
# Counted only (SYN counters), no listener -> falls through to policy drop.
CNT_TCP="21 22 23 25 80 110 139 143 443 445 587 1433 1521 2375 3306 3389 5432 5900 6379 8080 8443 9200 9418 11211 27017"
CNT_UDP="53 123 137 161 500 1900 5060 11211"

log() { printf '\033[1;36m==>\033[0m %s\n' "$*"; }
die() { printf '\033[1;31mERROR:\033[0m %s\n' "$*" >&2; exit 1; }

[[ $EUID -eq 0 ]] || die "must run as root"
command -v systemctl >/dev/null || die "systemd required"

# --- 1. Base packages and time --------------------------------------------
log "Installing packages"
export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
apt-get install -y -qq --no-install-recommends \
    nftables docker.io python3 jq rsync chrony ca-certificates

log "Setting timezone to UTC, enabling chrony"
timedatectl set-timezone UTC
systemctl enable --now chrony
systemctl enable --now docker

echo "$NODE_ID" > /etc/honeypot-node-id
mkdir -p "$PREFIX" "$DATA/snapshots" "$DATA/ipdump" /var/log/opencanary /usr/local/lib

# --- 2. Move SSH to the management port -----------------------------------
# Port 22 has to be freed so the honeypot can bind it.
# Debian 13 uses ssh.socket by default, where the port lives in the socket
# unit - NOT in sshd_config. Both cases are handled.
if [[ "$MOVE_SSH" == "yes" ]]; then
  if ss -tlnp 2>/dev/null | grep -q ":$MGMT_PORT "; then
    log "SSH already listening on $MGMT_PORT - skipped"
  elif systemctl is-enabled --quiet ssh.socket 2>/dev/null; then
    log "ssh.socket detected -> ListenStream on $MGMT_PORT"
    mkdir -p /etc/systemd/system/ssh.socket.d
    cat > /etc/systemd/system/ssh.socket.d/10-honeypot.conf <<EOF
[Socket]
ListenStream=
ListenStream=$MGMT_PORT
EOF
    systemctl daemon-reload
    systemctl restart ssh.socket
  else
    log "classic sshd -> port $MGMT_PORT via drop-in"
    mkdir -p /etc/ssh/sshd_config.d
    printf 'Port %s\n' "$MGMT_PORT" > /etc/ssh/sshd_config.d/10-honeypot.conf
    sshd -t || die "sshd config invalid, nothing applied"
    systemctl restart ssh
  fi
  ss -tlnp | grep -q ":$MGMT_PORT " \
    || die "SSH is not listening on $MGMT_PORT - ABORTING before the firewall locks you out"
  log "SSH confirmed on port $MGMT_PORT"
fi

# --- 3. nftables: counters and unique-source-IP sets ----------------------
# Dedicated table 'hp'. No 'flush ruleset', so Docker's own tables survive.
log "Generating nftables ruleset"
NFT=/etc/nftables.d/honeypot.nft
mkdir -p /etc/nftables.d
{
  echo "#!/usr/sbin/nft -f"
  echo "# generated by bootstrap.sh - do not edit by hand"
  echo "table inet hp"
  echo "delete table inet hp"
  echo "table inet hp {"
  echo "  set scan4 { type ipv4_addr; flags dynamic,timeout; timeout 30d; size 1048576; }"
  echo "  set scan6 { type ipv6_addr; flags dynamic,timeout; timeout 30d; size 262144; }"
  echo "  counter c_icmp {}"
  echo "  counter c_tcp_other {}"
  echo "  counter c_udp_other {}"
  for p in $CNT_TCP; do echo "  counter c_t$p {}"; done
  for p in $CNT_UDP; do echo "  counter c_u$p {}"; done
  echo "  chain input {"
  echo "    type filter hook input priority filter; policy drop;"
  echo "    iif \"lo\" accept"
  echo "    ct state established,related accept"
  # DHCP lease renewal - without this the node loses its address in a cloud net
  echo "    udp sport 67 udp dport 68 accept"
  echo "    udp sport 547 udp dport 546 accept"
  echo "    icmp type echo-request limit rate 10/second counter name c_icmp accept"
  echo "    icmpv6 type { echo-request, nd-neighbor-solicit, nd-neighbor-advert, nd-router-solicit, nd-router-advert } accept"
  # Management access first, so a counting mistake can never lock us out
  echo "    ip saddr $ADMIN_CIDR tcp dport $MGMT_PORT accept"
  # Unique source IPs: dynamic sets, exact and without log flooding
  echo "    meta nfproto ipv4 tcp flags syn / fin,syn,rst,ack update @scan4 { ip saddr }"
  echo "    meta nfproto ipv6 tcp flags syn / fin,syn,rst,ack update @scan6 { ip6 saddr }"
  # Per-port SYN counters (no verdict -> evaluation continues)
  for p in $CNT_TCP; do
    echo "    tcp flags syn / fin,syn,rst,ack tcp dport $p counter name c_t$p"
  done
  echo "    tcp flags syn / fin,syn,rst,ack tcp dport != { $(echo $CNT_TCP | tr ' ' ',') } counter name c_tcp_other"
  for p in $CNT_UDP; do echo "    udp dport $p counter name c_u$p"; done
  echo "    udp dport != { $(echo $CNT_UDP | tr ' ' ',') } counter name c_udp_other"
  # Let the emulated ports through; everything else hits policy drop
  echo "    tcp dport { $(echo $HP_TCP | tr ' ' ',') } accept"
  echo "  }"
  echo "}"
} > "$NFT"
chmod 0755 "$NFT"

nft -c -f "$NFT" || die "nftables ruleset is syntactically invalid"

# Own unit instead of nftables.service: ordered After=docker.service so the
# load order is deterministic and neither side clobbers the other's tables.
cat > /etc/systemd/system/hp-nft.service <<EOF
[Unit]
Description=Honeypot nftables counters
After=network-online.target docker.service
Wants=network-online.target
[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/usr/sbin/nft -f $NFT
[Install]
WantedBy=multi-user.target
EOF
systemctl daemon-reload
systemctl enable --now hp-nft.service
log "nftables active"

# --- 4. OpenCanary image --------------------------------------------------
IMG=honeypot-opencanary:pinned
if [[ -f "$SRC/image.tar" ]]; then
  log "Loading image from image.tar (byte-identical to the other nodes)"
  docker load -i "$SRC/image.tar"
elif docker image inspect "$IMG" >/dev/null 2>&1; then
  log "Image $IMG already present"
else
  log "Building image (FIRST node only - use docker save afterwards)"
  docker build -t "$IMG" "$SRC/opencanary"
  echo
  log "For the remaining nodes: docker save $IMG -o image.tar (copy the file along)"
fi

# --- 5. Config and container ---------------------------------------------
log "Writing OpenCanary config"
sed "s/__NODE_ID__/$NODE_ID/g" "$SRC/opencanary/opencanary.conf" > "$PREFIX/opencanary.conf"

cat > "$PREFIX/docker-compose.yml" <<EOF
name: honeypot
services:
  opencanary:
    image: $IMG
    container_name: opencanary
    # host networking is mandatory: with bridge + published ports the traffic
    # is DNATed in PREROUTING and traverses the forward path, so the input-hook
    # counters above would not see it.
    network_mode: host
    restart: unless-stopped
    volumes:
      - $PREFIX/opencanary.conf:/etc/opencanaryd/opencanary.conf:ro
      - /var/log/opencanary:/var/log/opencanary
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "3"
EOF

log "Starting container"
docker compose -f "$PREFIX/docker-compose.yml" up -d 2>/dev/null \
  || docker-compose -f "$PREFIX/docker-compose.yml" up -d

# --- 6. Snapshot timers --------------------------------------------------
log "Installing snapshot timers"
install -m 0755 "$SRC/bin/snapshot.sh" /usr/local/bin/hp-snapshot
install -m 0644 "$SRC/bin/hp_snapshot.py" /usr/local/lib/hp_snapshot.py

cat > /etc/systemd/system/hp-snapshot.service <<'EOF'
[Unit]
Description=Honeypot counter snapshot
[Service]
Type=oneshot
ExecStart=/usr/local/bin/hp-snapshot
EOF
cat > /etc/systemd/system/hp-snapshot.timer <<'EOF'
[Unit]
Description=Honeypot counter snapshot (hourly)
[Timer]
OnCalendar=hourly
Persistent=true
[Install]
WantedBy=timers.target
EOF
cat > /etc/systemd/system/hp-ipdump.service <<'EOF'
[Unit]
Description=Honeypot unique-source-IP dump
[Service]
Type=oneshot
ExecStart=/usr/local/bin/hp-snapshot --ipdump
EOF
cat > /etc/systemd/system/hp-ipdump.timer <<'EOF'
[Unit]
Description=Honeypot unique-source-IP dump (daily)
[Timer]
OnCalendar=daily
Persistent=true
[Install]
WantedBy=timers.target
EOF
systemctl daemon-reload
systemctl enable --now hp-snapshot.timer hp-ipdump.timer
/usr/local/bin/hp-snapshot   # write a baseline immediately

# --- 7. Fingerprint ------------------------------------------------------
MANIFEST="$DATA/manifest.txt"
{
  echo "node_id=$NODE_ID"
  echo "bootstrapped_utc=$(date -u +%FT%TZ)"
  echo "kernel=$(uname -r)"
  echo "os=$(. /etc/os-release && echo "$PRETTY_NAME")"
  echo "mgmt_port=$MGMT_PORT"
  echo "admin_cidr=$ADMIN_CIDR"
  echo "hp_tcp=$HP_TCP"
  echo "cnt_tcp=$CNT_TCP"
  echo "cnt_udp=$CNT_UDP"
  echo "sha256_opencanary_conf=$(sha256sum "$PREFIX/opencanary.conf" | cut -d' ' -f1)"
  echo "sha256_nft=$(sha256sum "$NFT" | cut -d' ' -f1)"
  echo "docker_image_id=$(docker image inspect -f '{{.Id}}' "$IMG")"
} > "$MANIFEST"

echo
log "DONE - $NODE_ID"
cat "$MANIFEST"
echo
cat <<EOF
Next steps:
  1. Verify from outside:  bin/verify-exposure.sh <ip-a> <ip-b> <ip-c> <ip-d>
     Port lists MUST be identical, otherwise the comparison is void.
  2. Let it burn in for 48h and exclude that window from the measurement.
  3. Record the measurement window start in $MANIFEST.
  4. Logs: /var/log/opencanary/opencanary.log , counters: $DATA/snapshots/
EOF
